### ISSUE TITLE
Fork of blogging blogofile_blog as well?

### ISSUE THREAD

**Issue by ianorlin** [wxl/blogofobe#1]
The blogofile to get a working project at least from the last documentation I have found it says to install blogophile-blog as well for the plugins if any apis or things must be changed or install locations like how it is still invoked with blogofile to build everything. 

In its current state blogofile_blog is installable on blogofobe but will it make life harder for all blogofobe devs if we can't break this or work around python breaking stuff in new versions?

**Comment by wxl** [comment]
[already done](https://github.com/wxl/blogofobe_blog), actually. ☺
