### ISSUE TITLE
blogofobe/docs/config_file.rst heirarchical cache link is not found

### ISSUE THREAD

**Issue by ianorlin** [wxl/blogofobe#5]
The blogofobing made the link not work as it still tries to have enigma curry place in the link. for hierachal cache and is trying to put in a link to http://github.com/EnigmaCurry/blogofobe/blob/master/blogofobe/cache.py#L22 

but that is not the correct place and 

s/EnigmaCurry/wxl/ also does not simply fix it.

**Comment by wxl** [comment]
fixed in 992bd4ad55de2bed4d08b40dc25dd1dec5a8b47b, and pointing at the current branch (plugins).
